### ISSUE TITLE
Can't install plugin 

### ISSUE THREAD

**Issue by SimonCowellP** [nexonic-official/nexonic-issue-tracker#1] opened 2020-04-06 04:08 UTC
Getting following error:

> We are unable to generate an trial license. The plugin key is invalid. Please contact us if the problem persists.

<img width="1093" alt="error" src="https://user-images.githubusercontent.com/63220895/78522243-960ad400-7781-11ea-861c-2cd8809fb560.png">

**Comment by nexonic-official** [comment] 2020-04-23 06:16
Hi Simon, We apologies for the delay in replying back, as we see the issue is happening while a trial license generated by Atlassian for their cloud and data center version.
We contacted their support and understood that there was a bug with their licensing and they are working with us to resolve the issue.
We are hoping to get this resolved in a day or 2 - we ll update you as this is resolved and plugin is ready to get installed.

Thanks for your help.

**Comment by nexonic-official** [comment] 2020-04-28 07:13
Hi Simon, hope you are doing well, Just like to update that our server plugin is now available trial.

here is the documentation link of our plugins and mobile apps.
https://nexonic.atlassian.net/wiki/spaces/DOC/pages/214892551/Artify+by+Nexonic+for+JIRA+Documentation+Home

Please let us know if you like to schedule a demo with us, we will be happy to provide all details needed.

Thanks

**Closed as completed by nexonic-official** 2020-04-28 07:13 UTC
